### ISSUE TITLE
Wonderfulsubs addon stopped working on multiple titles

### ISSUE THREAD

**Issue by Miwer** [DxCx/plugin.video.wonderfulsubs#116]
Hi,

I was just wondering if anyone else had issues with playing back titles on Wonderfulsubs. It seems after I upgraded the plugin to the latest version a few days ago, I cannot play some of the titles I'm currently watching. Even thoses I have already seen won't play anymore.

Attack on titan: Plays fine before and after
Nana: Was working, will not play now
ReLife: Was working, will not play now
Amagami SS: Was not working before (no eligible sources), will not play now

When I write "will not play", it's like it's finding sources and trying to play, but then just quits back to the episode list. I do not get a list of sources to choose from.

I have posted a log here: [https://pastebin.com/raw/rjj84DHA](https://pastebin.com/raw/rjj84DHA)

In the debug log it seems like I'm getting a "400 bad request" - could this be related to the Agent header change recently ?  Issue #112

**Comment by HatHeadNinja** [comment]
Hello!

Firstly, thank you to the devs and folks who made and maintain this plugin: really awesome and appreciated! 

Want to report the same issue as Miwer above.

If anyone needs more specific examples, please let me know and I'll post some.

**Comment by Ichijoe2112** [comment]
It was finally working with the last v27 release. But, following my now closed thread. It seems like Me RedNijaX had to close his server off do to increased traffic. Hopefully he can find a better work around.

But, with Kodi v19 seemingly 'round the corner, and with that the untimely death of all Python v2.0 code. (e.g. insert your favorite Addon here!). There is plenty of warning that these Addons will all need to be redone for Python v3.0 now. I have no idea how that would affect say this project. But, again this is hardy the only Addon out there. And, more of these Addons are all tending to be abandoned, and forgotten now.

**Comment by DxCx** [comment]
Redo in python 3 is no problem...
Also, if title is not working you can try and right click then 'Alt Search' which usually works (searches outside of wonderfulsubs)

Anyway, there is no issue i am familiar with.. @RedNinjaX @SwagOtaku

**Comment by RedNinjaX** [comment]
@DxCx I've made some modifications server side to reduce load on the server as it was starting to crash a lot.

Just set the user agent back to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36` and add a new header called `Platform` and set its value to `Kodi`

It will automatically start working again after that.

**Comment by Ichijoe2112** [comment]
Just out of interest how, or where do I have to input: 'Platform = Kodi'?

**Comment by RedNinjaX** [comment]
You can't. It has to be done through the source code

**Comment by doko-desuka** [comment]
I can do the PR for this, but I don't recommend this mechanism as this 'Platform' header will have to be put in the link sent to Kodi for streaming (that `makeKodiHeaders()` function).  
This means FFMpeg will use this header all the time when requesting the chunks, and the source will happen to see a strange "Platform: Kodi" header in the requests they're getting. What they do about this (e.g. increase their security), it's up to them.

My suggestion: if you only want to give special treatment to the Kodi add-on and not any external apps that are snooping in, it'll be difficult because the add-on is open-source and anyone can just go and read the source on how to do it. A closed source app would be slightly better for this (but even then anyone can snoop the requests it's sending out, or decompile the APK in case of Android to see how it works).  

In any case, I'd do it with an optional URL parameter that only the add-on knows about: your `/media/playlist?type=playlist&quality=(...)` link needs to have a "&platform=kodi", appended by the add-on, to actually get that special treatment.

**Comment by doko-desuka** [comment]
> and add a new header called `Platform` and set its value to `Kodi`

I tried doing that but it turns out that non-standard HTTP headers are ignored by FFMpeg on Kodi 17.6, as seen here in the source code:
https://github.com/xbmc/xbmc/blob/Krypton/xbmc/filesystem/CurlFile.cpp#L854-L859

In Kodi 18+ they do let you use whatever headers you want:
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L834-L837

So if you want to support Kodi 17.6 users (besides that problem with using these custom headers directly with the source that I mentioned before), a different way is needed.  
That hidden parameter in the source URL would be safe enough.

**Comment by RedNinjaX** [comment]
@DxCx I've opened up a pull request that adds a platform parameter to the stream endpoint. Once that's merged I can take care of the rest. Whenever you're ready

**Comment by mickgibson** [comment]
I have upgraded Windows, Kodi, and Wounderfulsubs and I still only have 4 that are some of the last season that play - Black Clover, GeGeGe no Kitaro, Dr Stone, and Even no Shouboutai. All the others that are now this season and old seasons that loaded in this season will not play.

**Comment by HatHeadNinja** [comment]
> I have upgraded Windows, Kodi, and Wounderfulsubs and I still only have 4 that are some of the last season that play - Black Clover, GeGeGe no Kitaro, Dr Stone, and Even no Shouboutai. All the others that are now this season and old seasons that loaded in this season will not play.

I am experiencing the same issues as Mick. 

Please let me know if anyone requires more details or if I can help in any non-programming tasks!

**Comment by Tony322** [comment]
Not sure if related, but addon stopped working for me and the follwing steps made it work again for me. 1. Reinstall and 2 (what i think actuqlly made it work) was going into the settings of the addon and cleared cache and settings. Arter that it started working again for me! :)

**Comment by HatHeadNinja** [comment]
> Not sure if related, but addon stopped working for me and the follwing steps made it work again for me. 1. Reinstall and 2 (what i think actuqlly made it work) was going into the settings of the addon and cleared cache and settings. Arter that it started working again for me! :)

Thanks, @Tony322!  I am still having the same issue after re-install and settings clear.

For example, does One Punch Man dub episode 8 work for you?

**Comment by Jkrise** [comment]
I have had similar issues recently, I know these guys are working hard to get us our anime so in the mean time I have had a lot of luck using alt search when things did not work normally.

**Comment by zrkd51** [comment]
Hi!, Yesterday I noticed after updating the Common Cache Plugin to version 2.6.0, that episodes were loading with no audio, unless I restarted Kodi. Today , I see no new episodes for this week. Is somebody else having the same issue? Is this related to the Common Cache Plugin update?

**Comment by clutchylfg** [comment]
After update and clearing settings mine is working, thanks for the tip @Tony322

**Comment by doko-desuka** [comment]
Can you guys clear up one thing? There are several sources: DASH, HLS and "HD".  
The "HD" one is the one that needs fixes (I already told @RedNinjaX over on Discord how to address this). The other sources should be working.

**Comment by mickgibson** [comment]
I started over! I put the newest Kodi 18.5 and only Wounderfulsubs 0.0.28 and I am only 25% of the Anime to run! The ones who have Dash and HLS run, any other that pops up that I do not select the format DOES NOT.

**Comment by RedNinjaX** [comment]
Should be working now

**Comment by Ichijoe2112** [comment]
Execpt that it's not...
