### ISSUE TITLE
WonderfulSubs add-on not working

### ISSUE THREAD

**Issue by W94545** [DxCx/plugin.video.wonderfulsubs#130]
Hello. May I ask is WonderfulSubs down right now? I have it on Kodi via Firestick. Add-on is currently not opening titles. Keep getting error message. It was working just fine earlier this morning.

**Comment by W94545** [comment]
Update: It's working now.

**Comment by Shahav** [comment]
Hello DxCx......
Also do you have a new repo address that I can plug into file manager cause
the old https://beta.wonderfulsubs.com/kodi that we used during the beta
testing of course doesn't work anymore.  And, for some reason when I try to
DL the zip file to my download folder in external storage it never shows
up; so that is why I was wondering about a repo address.
Sherry
